In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/windTunnel/test 1/4130_19x10_RUN1.csv')
df.head()

,RUN,TP,CODE,DYNAMIC PRESSURE,TS Temp,BALANCE Temp,N1,N2,S1,S2,A1,R1,Lift,Drag,Pitch,Yaw,Side,Roll
0,1.0,1.0,1.0,0.000,0.000,0.000,0.118,0.161,-0.073,0.117,-0.397,24.928,-46.761,-16.693,16.272,40.161,-6.807,0.0
1,1.0,2.0,1.0,0.000,0.000,0.000,0.118,0.161,-0.073,0.117,-0.397,24.928,-46.755,-16.692,16.271,40.157,-6.804,0.0
2,1.0,3.0,0.0,0.158,73.842,82.754,-0.001,0.001,-0.001,0.001,0.054,0.000,0.033,2.129,0.343,0.358,-0.091,0.0
3,1.0,4.0,0.0,0.174,72.349,81.432,-0.001,0.000,-0.001,-0.001,-0.104,0.000,0.066,-4.137,0.386,0.041,0.224,0.0
4,1.0,5.0,0.0,0.177,71.893,81.390,-0.001,0.000,-0.000,-0.001,-0.120,0.000,0.055,-4.763,0.356,-0.291,0.235,0.0

In [9]:
df[df["TP"] == 23].iloc[0]

RUN                  1.000
TP                  23.000
CODE                 0.000
DYNAMIC PRESSURE     0.267
TS Temp             70.157
BALANCE Temp        81.440
N1                   0.000
N2                  -0.002
S1                  -0.003
S2                  -0.003
A1                  -0.368
R1                   0.000
Lift                 0.281
Drag               -14.644
Pitch               -0.059
Yaw                 -0.116
Side                 0.831
Roll                 0.000
Name: 22, dtype: float64